### PR TITLE
Fix #1873 - Fix frame not being drawn on the timeline

### LINKED ISSUE #1873: Timeline frame disappear
### Issue Summary

https://github.com/user-attachments/assets/b9412e71-63cc-4c0f-b524-2d785d178a1e

In the video above you can see that after the timeline selection is deselected, the current frame disappear from the timeline.
Although the frame will re-appear if you click on the frame.

### Actual Results
The last frame disappear when the timeline selection is undone

### Expected Results
The last frame not disappearing

### Steps to reproduce
1. Draw a stroke on keyframe 1
2. Create a new keyframe on pos 2
3. Select both keyframes on the timeline
4. Draw a stroke on pos 2
5. undo the action

### System Information
+ Pencil2D Version: 0.7.0

### PR DESCRIPTION
**Pull request by MrStevns**
The reason for this is that while we keep a list of selected keyframes to move and paint on the timeline, a keyframe also has its own "isSelected" state. This state is backed up through undo/redo operations while the layer::getSelectedFrames is not.
We use the isSelected state to ignore selected frames in the TimeLineCells::paintFrames while we use Layer::getSelectedFrames() to paint the selected frames.

This means that we can get into a situation where the frame is neither painted as selected nor non selected because of the two different sources of truth.

The solution is to remove one of the sources. As such, I went ahead and removed isSelected from Keyframe, so there's only one truth. By doing so, said frames can no longer be put in a selected state through undo/redo operations, which I personally think is good. I've inspected a few other applications which does also not keep selections as undo/redo'able state.

There's also the benefit that we don't have to iterate through all frames to know which is selected.

To that end my conclusion is that we shouldn't have to do that either.

fixes https://github.com/pencil2d/pencil/issues/1873

### CODE REVIEW

**Comment by chchwy** [comment]
Totally agree with you about removing "isSelected" from Keyframe.

File: app/src/timelinecells.cpp [hunk 1]
```diff
@@ -444,12 +444,19 @@ void TimeLineCells::paintFrames(QPainter& painter, QColor trackCol, const Layer*
 
     int recHeight = height - 4;
 
-    layer->foreachKeyFrame([&](KeyFrame* key)
+    const QList<int> selectedFrames = layer->getSelectedFramesByPos();
+    for (auto pair : layer->keyframes())
```
Comment (chchwy) [inline app/src/timelinecells.cpp:448]: Doesn't the original `layer->foreachKeyFrame()` fit your need here?

Comment (MrStevns) [reply app/src/timelinecells.cpp]: Ah.. yes that's right.. I forgot about that.
I've fixed it now.

File: core_lib/src/structure/layer.h [hunk 2]
```diff
@@ -170,6 +170,8 @@ class Layer
     /** Clear the list of dirty keyframes */
     void clearDirtyFrames() { mDirtyFrames.clear(); }
 
+    std::map<int, KeyFrame*, std::greater<int>> keyframes() const { return mKeyFrames; }
```
Comment (chchwy) [inline core_lib/src/structure/layer.h:173]: Could you please remove this unused function?

I don't want to expose the internal data structure outside the Layer class. Looking back, my decision to use std::map instead of std::vector wasn't very smart in hindsight.

**Review by chchwy — APPROVED** [review]

**Comment by chchwy** [comment]
Apart from the clean up mentioned above, I don't have further questions. Thanks and well done @MrStevns

File: core_lib/src/structure/layer.h (hunk 2 above)
Comment (MrStevns) [reply core_lib/src/structure/layer.h]: Done

Comment (chchwy) [reply core_lib/src/structure/layer.h]: thanks!
