### PR TITLE
Fix #1195 check for updates failure

### LINKED ISSUE #1195: Update checker fails to probe current version (0.6.3) and displays an error message
### Issue Summary

It seems checking for updates in v0.6.3 prompts the user with an error message as it's trying to see if the current version is lower than itself.

### Expected Results

Ideally It should say something along the lines of "your version is up to date" when probing the current download version.

### Video or Image Reference

Candyface tested that the feature works in 0.6.2 (macOS) but he was using the Qt version.
image

For for myself, on Windows using the release download version it hosts the error
image

### Steps to reproduce

1. Go to the HELP menu
2. Press the "Check for Updates" action
3. Wait for it to populate the progress bar. It will show an error.

Note: If it doesn't report an error, please comment your operating system.

### System Information
+ Pencil2D Version:

Version: 0.6.3
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

### PR DESCRIPTION
**Pull request by chchwy**
Addressing #1195

1. Now the version info request link is HTTPS (HTTP doesn't work anymore)
2. Deploy OpenSSL DLLs in our Windows CI process.

Note: 
The current Qt version (5.12) uses OpenSSL 1.1.1d
AppVeyor has OpenSSL pre-installed 
https://www.appveyor.com/docs/windows-images-software/

### CODE REVIEW

File: app/src/checkupdatesdialog.cpp [hunk 1]
```diff
@@ -1,4 +1,4 @@
-#include "checkupdatesdialog.h"
+﻿#include "checkupdatesdialog.h"
```
Comment (J5lx) [inline app/src/checkupdatesdialog.cpp:1]: Is this intentional? Back in #683, you yourself said no BOM was preferable for better cross-platform compatibility. Seen this on a bunch of your commits lately.

**Comment by J5lx** [comment]
Seems to work fine with both the AppImage and the Windows build (on Wine at least…) 👍

File: app/src/checkupdatesdialog.cpp (hunk 1 above)
Comment (chchwy) [reply app/src/checkupdatesdialog.cpp:1]: Damn it, must be my editor. I will remove the BOM
